Allow 'whitelisting' of components in panlint
quattor/pan pull request #225
Opened 2019-11-21 08:41 UTC by wpoely86

Panlint will not issue errors about the missing include for any component in the whitelist.

2019-11-21 08:42 UTC, wpoely86 commented
@stdweird have a look

2019-11-21 08:53 UTC, ned21 commented
What's the use case for this?

2019-11-21 08:57 UTC, wpoely86 commented
I find the `Component X in use, but component config has not been included` errors not really helpful. Especially with metaconfig. It means including a lot of extra lines and it doesn't say anything about including the schema.

So far I've mostly ignored the message but now we have Jenkins that is not happy because of it. This allows a way to get around it.

2021-06-28 12:29 UTC, ned21 requested changes
"whitelist" is not inclusive language - can you please rename all instances of it in this code? Given that it's really about ignoring a specific test, perhaps --ignore-missing-component-config would be a better name?

Although I also have concerns about this being a special case of a general issue, and a more configuration option would make sense?

2021-06-28 12:44 UTC, jrha commented
Additionally, can you add tests for whatever you implement please.

2024-10-24 09:50 UTC, jrha commented on panc/src/main/scripts/panlint/panlint.py
> +def lint_file(filename, allow_mvn_templates=False, whitelist_components=None):
```suggestion
def lint_file(filename, allow_mvn_templates=False, ignore_components=None):
```

2024-10-24 09:50 UTC, jrha commented on panc/src/main/scripts/panlint/panlint.py
> +        whitelist_components = []
```suggestion
    if ignore_components is None:
        ignore_components = []
```

2024-10-24 09:50 UTC, jrha commented on panc/src/main/scripts/panlint/panlint.py
> +    components_included.extend(whitelist_components)
```suggestion
    # add ignored components
    components_included.extend(ignore_components)
```

2024-10-24 09:50 UTC, jrha commented on panc/src/main/scripts/panlint/panlint.py
> +    parser.add_argument('--whitelist-components', type=str,
```suggestion
    parser.add_argument('--ignore-components', type=str,
```

2024-10-24 09:50 UTC, jrha commented on panc/src/main/scripts/panlint/panlint.py
> +        whitelist_components = args.whitelist_components.split(',')
```suggestion
    ignore_components = None
    if args.ignore_components:
        ignore_components = args.ignore_components.split(',')
```

2024-10-24 09:50 UTC, jrha commented on panc/src/main/scripts/panlint/panlint.py
> +            file_reports, file_problems = lint_file(filename, args.allow_mvn_templates, whitelist_components)
```suggestion
            file_reports, file_problems = lint_file(filename, args.allow_mvn_templates, ignore_components)
```

2024-10-27 02:39 UTC, ned21 commented
Looking good - can you please squash the commits and amend the commit message of 7c891c0bca4673daf00c596772b596e978d3a99c?

2024-11-07 16:10 UTC, wpoely86 commented
@ned21 good to go

2024-11-07 23:46 UTC, ned21 approved these changes

2024-11-07 23:46 UTC, ned21 commented
Approved. Do we have a plan to do a new release of panc to include the updated panlint? Or do we just recommend sites use it from HEAD?

2024-11-08 11:09 UTC, merged

2024-11-08 11:19 UTC, jrha commented
Sometime after the next general release yes, but I'd say using it from HEAD is fine too.